# Generated by Django 4.1.13 on 2024-03-14 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('website', models.URLField()),
                ('noOfYears', models.IntegerField()),
                ('noOfStudents', models.IntegerField()),
                ('collegeType', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CollegeAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('preferences', models.TextField()),
                ('gradeInHighSchool', models.CharField(max_length=100)),
                ('highSchoolSystem', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UniversityAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('establishedAt', models.DateField()),
                ('admin', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.universityadmin')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('thresholdGpa', models.FloatField()),
                ('colleges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.college')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('maxStudents', models.IntegerField()),
                ('creditHours', models.IntegerField()),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.department')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.collegeadmin'),
        ),
        migrations.AddField(
            model_name='college',
            name='universities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.university'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('colleges', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.college')),
            ],
        ),
    ]
