# Generated by Django 4.1.13 on 2024-06-26 16:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('college', models.CharField(blank=True, max_length=50, null=True)),
                ('university', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('BriefHistory', models.TextField()),
                ('Website', models.URLField()),
                ('noOfYears', models.IntegerField()),
                ('noOfStudents', models.IntegerField()),
                ('collegeType', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
                ('AdmissionCertificates', models.CharField(max_length=200)),
                ('AdmissionRequirements', models.CharField(max_length=200)),
                ('CreditHours', models.CharField(max_length=20)),
                ('Departments', models.CharField(max_length=220)),
                ('FacebookPage', models.CharField(max_length=100)),
                ('FacultyDeans', models.CharField(max_length=100)),
                ('MasterPrograms', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('SpecializationYear', models.CharField(max_length=100)),
                ('YearFounded', models.CharField(max_length=50)),
                ('university', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField(default=datetime.date(2000, 1, 1))),
                ('highSchoolSystem', models.CharField(max_length=100)),
                ('governorate', models.CharField(default='Cairo', max_length=100)),
                ('gradeInHighSchool', models.CharField(max_length=100)),
                ('preferences', models.TextField()),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UniversityAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('description', models.TextField()),
                ('FacebookPage', models.CharField(max_length=100)),
                ('Fax', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=50)),
                ('Rank', models.CharField(max_length=10)),
                ('UniversityPresidents', models.CharField(max_length=50)),
                ('Website', models.CharField(max_length=50)),
                ('YearFounded', models.CharField(max_length=50)),
                ('admin', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.universityadmin')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('thresholdGpa', models.FloatField()),
                ('colleges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.college')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('maxStudents', models.IntegerField()),
                ('creditHours', models.IntegerField()),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.department')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='admin',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.collegeadmin'),
        ),
    ]
