# Generated by Django 4.1.13 on 2024-03-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='id',
            new_name='_id',
        ),
    ]
