# Generated by Django 4.1.13 on 2024-03-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_id_college__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='admin',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.collegeadmin'),
        ),
        migrations.AlterField(
            model_name='college',
            name='universities',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.university'),
        ),
    ]
