# Generated by Django 4.1.13 on 2024-07-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_announcement_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="universityName",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="collegeadmin",
            name="name",
            field=models.CharField(default="collegeadminname", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="universityadmin",
            name="name",
            field=models.CharField(default="universityadminname", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="announcement",
            name="university",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="college",
            name="FacultyDeans",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="college",
            name="MasterPrograms",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="college",
            name="collegeType",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="college",
            name="fees",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="college",
            name="noOfStudents",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="university",
            name="Fax",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="university",
            name="PhoneNumber",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="university",
            name="UniversityPresidents",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="university",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
